from spm.__wrap__ import _Runtime


def spm_eeg_firstlevel(*args, **kwargs):
  """  Convolution modelling for M/EEG data  
    FORMAT D = spm_eeg_firstlevel(S)  
     
      S - job structure generated by spm_cfg_eeg_firstlevel  
   __________________________________________________________________________  
    Reference:  
    Litvak V, Jha A, Flandin G, Friston K. Convolution models for induced  
    electromagnetic responses. Neuroimage. 2013, 64:388-98  
   __________________________________________________________________________  
  

  [Link to the Matlab implementation.](https://github.com/spm/spm/blob/main/spm_eeg_firstlevel.m)
  """

  return _Runtime.call("spm_eeg_firstlevel", *args, **kwargs)
