from spm.__wrapper__ import Runtime


def spm_eeg_firstlevel(*args, **kwargs):
    """
      Convolution modelling for M/EEG data  
        FORMAT D = spm_eeg_firstlevel(S)  
         
          S - job structure generated by spm_cfg_eeg_firstlevel  
       __________________________________________________________________________  
        Reference:  
        Litvak V, Jha A, Flandin G, Friston K. Convolution models for induced  
        electromagnetic responses. Neuroimage. 2013, 64:388-98  
       __________________________________________________________________________  
      

    [Matlab code]( https://github.com/spm/spm/blob/main/spm_eeg_firstlevel.m )

    Copyright (C) 2024-2024 Functional Imaging Laboratory, Department of Imaging Neuroscience, UCL
    """
    return Runtime.call("spm_eeg_firstlevel", *args, **kwargs)
