from .DEMO_dcm_fmri_nnm import DEMO_dcm_fmri_nnm
from .DEMO_model_reduction_ERP import DEMO_model_reduction_ERP
from .__NMDA_NMM_MFM import *
from .Neural_demo import Neural_demo
from .ROBOT_NMM import ROBOT_NMM
from .spm_csd_demo import spm_csd_demo
from .spm_dcm_Granger_asymmetry_demo import spm_dcm_Granger_asymmetry_demo
from .spm_dcm_Granger_demo import spm_dcm_Granger_demo
from .spm_dcm_prior_responses import spm_dcm_prior_responses
from .spm_delays_demo import spm_delays_demo
from .spm_demo_proceed import spm_demo_proceed
from .spm_erp2csd_demo import spm_erp2csd_demo
from .spm_freqs import spm_freqs
from .spm_fx_hh import spm_fx_hh
from .spm_fx_lfp import spm_fx_lfp
from .spm_fx_mfm_ensemble import spm_fx_mfm_ensemble
from .spm_gx_hh import spm_gx_hh
from .spm_gx_mfm import spm_gx_mfm
from .spm_ind_demo import spm_ind_demo
from .spm_induced_optimise import spm_induced_optimise
from .spm_induced_optimise_parameters import spm_induced_optimise_parameters
from .spm_lfp_demo import spm_lfp_demo
from .spm_lfp_log import spm_lfp_log
from .spm_lfp_mtf import spm_lfp_mtf
from .spm_lfp_priors import spm_lfp_priors
from .spm_lfp_sqrt import spm_lfp_sqrt
from .spm_mfa import spm_mfa
from .spm_mfa_G import spm_mfa_G
from .spm_mfa_bi import spm_mfa_bi
from .spm_mfa_bi_multi import spm_mfa_bi_multi
from .spm_mfa_demo import spm_mfa_demo
from .spm_mfm_demo import spm_mfm_demo
from .spm_mtf_demo import spm_mtf_demo
from .spm_neil import spm_neil
from .spm_nested_oscillations_demo import spm_nested_oscillations_demo
from .spm_nmda_priors import spm_nmda_priors
from .spm_opt_bfun import spm_opt_bfun
from .spm_seizure_demo import spm_seizure_demo
from .spm_sigmoid_demo import spm_sigmoid_demo

