from spm.__wrapper__ import Runtime


def _ft_datatype_dip(*args, **kwargs):
    """
      FT_DATATYPE_DIP descripts the FieldTrip MATLAB structure for dip data  
         
        The dip structure represents a dipole model that has been fitted to  
        ERP or ERF data using a non-linear optimization approach. It is  
        usually generated by the FT_DIPOLEFITTING function.  
         
        FIXME more information should be added here  
         
        See also FT_DATATYPE, FT_DATATYPE_SOURCE, FT_DATATYPE_VOLUME  
      

    [Matlab code]( https://github.com/spm/spm/blob/main/external/fieldtrip/fileio/private/ft_datatype_dip.m )

    Copyright (C) 2024-2024 Functional Imaging Laboratory, Department of Imaging Neuroscience, UCL
    """
    return Runtime.call("ft_datatype_dip", *args, **kwargs)
