name: Compile SPM
on:
  workflow_dispatch:

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
jobs:
  compile:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        version: ["2020b", "R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a", "R2024b"]

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:          
          cache: True
          release: ${{ matrix.version }}
          products: MATLAB_Compiler
          
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Run MPython
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('.mpython')); 
            spm_make_python(true, false); 
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spm-archive-${{ matrix.version }}
          path: ./spm/_spm/_spm.ctf
          retention-days: 1
          
