name: Compile SPM
on:
  workflow_call:
    inputs:
      matlab-version:
        required: true
        type: string

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
  
jobs:
  compile:
    runs-on: "ubuntu-latest"
    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:          
          cache: True
          release: ${{ inputs.matlab-version }}
          products:  |
            MATLAB_Compiler
            MATLAB_Compiler_SDK
          
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Run MPython
        uses: matlab-actions/run-command@v2
        with:
          command: |
            cd('.mpython'); 
            addpath(genpath('.')); 
            spm_make_python('.', true, false); 
