name: Wrap SPM
on:
  workflow_dispatch:

env:
  MLM_LICENSE_TOKEN: ${{ secrets.MATLAB_BATCH_TOKEN }}
jobs:
  wrap:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # This actions compiles by default with the newest available matlab version
        version: ["latest"] # ["R2021a", "R2021b", "R2022a", "R2022b", "R2023a", "R2023b", "R2024a", "R2024b"]
        os: ["ubuntu-latest", "macos-13", "macos-latest", "windows-latest"] # macos-13 has Intel architecture, macos-latest has Apple Silicon
        include: # These includes are just giving the OSs additional names
          - os: ubuntu-latest
            os_name: Linux
          - os: macos-13
            os_name: macOS_Intel
          - os: macos-latest
            os_name: macOS_Apple_Silicon
          - os: windows-latest
            os_name: Windows

    steps:
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{matrix.version}}
          products: MATLAB_Compiler
          
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Run MPython
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('.mpython')); 
            spm_make_python; 

      
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: runtime-${{ matrix.os }}
      #     path: ./spm/_spm/resources/*
      #     retention-days: 1
          
