from .ADEM_SHC_demo import ADEM_SHC_demo
from .ADEM_cost_SHC import ADEM_cost_SHC
from .ADEM_cued_response import ADEM_cued_response
from .ADEM_eyeblink import ADEM_eyeblink
from .ADEM_learning import ADEM_learning
from .ADEM_lorenz import ADEM_lorenz
from .ADEM_lorenz_entropy import ADEM_lorenz_entropy
from .ADEM_lorenz_surprise import ADEM_lorenz_surprise
from .ADEM_motor import ADEM_motor
from .ADEM_mountaincar_loss import ADEM_mountaincar_loss
from .ADEM_observe import ADEM_observe
from .ADEM_occlusion import ADEM_occlusion
from .ADEM_occulomotor_delays import ADEM_occulomotor_delays
from .ADEM_plaid import ADEM_plaid
from .ADEM_pursuit import ADEM_pursuit
from .ADEM_reaching import ADEM_reaching
from .ADEM_salience import ADEM_salience
from .ADEM_sample_image import ADEM_sample_image
from .ADEM_visual import ADEM_visual
from .ADEM_writing import ADEM_writing
from .ALAP_demo_attenuation import ALAP_demo_attenuation
from .DATA_COVID_JHU import DATA_COVID_JHU
from .DATA_COVID_UK import DATA_COVID_UK
from .DATA_COVID_US import DATA_COVID_US
from .DATA_WID_data import DATA_WID_data
from .DEMO_AI_NLSI import DEMO_AI_NLSI
from .DEMO_BAYES_FACTORS import DEMO_BAYES_FACTORS
from .DEMO_BMR_PEB import DEMO_BMR_PEB
from .DEMO_CVA_RSA import DEMO_CVA_RSA
from .DEMO_DCM_MB import DEMO_DCM_MB
from .DEMO_DCM_PEB import DEMO_DCM_PEB
from .DEMO_DCM_PEB_FIT import DEMO_DCM_PEB_FIT
from .DEMO_GROUP_PEB import DEMO_GROUP_PEB
from .DEMO_Lindley_paradox import DEMO_Lindley_paradox
from .DEMO_MDP_Stroop import DEMO_MDP_Stroop
from .DEMO_MDP_Understanding import DEMO_MDP_Understanding
from .DEMO_MDP_maze import DEMO_MDP_maze
from .DEMO_MDP_maze_X import DEMO_MDP_maze_X
from .DEMO_MDP_questions import DEMO_MDP_questions
from .DEMO_MDP_voice import DEMO_MDP_voice
from .DEMO_SLR import DEMO_SLR
from .DEMO_niche_construction import DEMO_niche_construction
from .DEM_CLIMATE_India import DEM_CLIMATE_India
from .DEM_COVID import DEM_COVID
from .DEM_COVID_AGE import DEM_COVID_AGE
from .DEM_COVID_COUNTRY import DEM_COVID_COUNTRY
from .DEM_COVID_DASH import DEM_COVID_DASH
from .DEM_COVID_I import DEM_COVID_I
from .DEM_COVID_LTLA import DEM_COVID_LTLA
from .DEM_COVID_S import DEM_COVID_S
from .DEM_COVID_T import DEM_COVID_T
from .DEM_COVID_UK import DEM_COVID_UK
from .DEM_COVID_UK4 import DEM_COVID_UK4
from .DEM_COVID_UTLA import DEM_COVID_UTLA
from .DEM_COVID_WID import DEM_COVID_WID
from .DEM_COVID_X import DEM_COVID_X
from .DEM_Dispatches import DEM_Dispatches
from .DEM_FEP_Least_Action import DEM_FEP_Least_Action
from .DEM_FEP_Lorenz import DEM_FEP_Lorenz
from .DEM_HB_and_LE import DEM_HB_and_LE
from .DEM_Immune import DEM_Immune
from .DEM_MDP_decision import DEM_MDP_decision
from .DEM_SARS import DEM_SARS
from .DEM_SARS_I import DEM_SARS_I
from .DEM_Stephen import DEM_Stephen
from .DEM_birdsong import DEM_birdsong
from .DEM_cells import DEM_cells
from .DEM_cells_cells import DEM_cells_cells
from .DEM_coupled_oscillators import DEM_coupled_oscillators
from .DEM_dSprites import DEM_dSprites
from .DEM_demo import DEM_demo
from .DEM_demo_ALAP import DEM_demo_ALAP
from .DEM_demo_Bayesian_Model_Reduction import DEM_demo_Bayesian_Model_Reduction
from .DEM_demo_Cornsweet import DEM_demo_Cornsweet
from .DEM_demo_DCM_LAP import DEM_demo_DCM_LAP
from .DEM_demo_DEM import DEM_demo_DEM
from .DEM_demo_DFP import DEM_demo_DFP
from .DEM_demo_EM import DEM_demo_EM
from .DEM_demo_GF_and_KF import DEM_demo_GF_and_KF
from .DEM_demo_GLM import DEM_demo_GLM
from .DEM_demo_Gabor import DEM_demo_Gabor
from .DEM_demo_LAP import DEM_demo_LAP
from .DEM_demo_Lagrangian import DEM_demo_Lagrangian
from .DEM_demo_Lagrangian_flow import DEM_demo_Lagrangian_flow
from .DEM_demo_Lorenz import DEM_demo_Lorenz
from .DEM_demo_MDP_DEM import DEM_demo_MDP_DEM
from .DEM_demo_MDP_X import DEM_demo_MDP_X
from .DEM_demo_MDP_XX import DEM_demo_MDP_XX
from .DEM_demo_MDP_fit import DEM_demo_MDP_fit
from .DEM_demo_MDP_fit_fields import DEM_demo_MDP_fit_fields
from .DEM_demo_MDP_habits import DEM_demo_MDP_habits
from .DEM_demo_MDP_maze import DEM_demo_MDP_maze
from .DEM_demo_MDP_reading import DEM_demo_MDP_reading
from .DEM_demo_MDP_rule import DEM_demo_MDP_rule
from .DEM_demo_MDP_search import DEM_demo_MDP_search
from .DEM_demo_MMN import DEM_demo_MMN
from .DEM_demo_MMN_deviance import DEM_demo_MMN_deviance
from .DEM_demo_MMN_gen import DEM_demo_MMN_gen
from .DEM_demo_OU import DEM_demo_OU
from .DEM_demo_PEB import DEM_demo_PEB
from .DEM_demo_Posner import DEM_demo_Posner
from .DEM_demo_SOC import DEM_demo_SOC
from .DEM_demo_connectivity_fMRI import DEM_demo_connectivity_fMRI
from .DEM_demo_contact_lens import DEM_demo_contact_lens
from .DEM_demo_convolution import DEM_demo_convolution
from .DEM_demo_convolution_LAP import DEM_demo_convolution_LAP
from .DEM_demo_dendrite import DEM_demo_dendrite
from .DEM_demo_double_well import DEM_demo_double_well
from .DEM_demo_doublewell_LAP import DEM_demo_doublewell_LAP
from .DEM_demo_duet import DEM_demo_duet
from .DEM_demo_fMRI_HMM import DEM_demo_fMRI_HMM
from .DEM_demo_fMRI_PEB import DEM_demo_fMRI_PEB
from .DEM_demo_face_inference import DEM_demo_face_inference
from .DEM_demo_factor_analysis import DEM_demo_factor_analysis
from .DEM_demo_filtering import DEM_demo_filtering
from .DEM_demo_hdm import DEM_demo_hdm
from .DEM_demo_hdm_LAP import DEM_demo_hdm_LAP
from .DEM_demo_hdm_SCK import DEM_demo_hdm_SCK
from .DEM_demo_hierarchical_optmisation import DEM_demo_hierarchical_optmisation
from .DEM_demo_induced_fMRI import DEM_demo_induced_fMRI
from .DEM_demo_large_fMRI import DEM_demo_large_fMRI
from .DEM_demo_lorenz_LAP import DEM_demo_lorenz_LAP
from .DEM_demo_modes_fMRI import DEM_demo_modes_fMRI
from .DEM_demo_ontology import DEM_demo_ontology
from .DEM_demo_psychosis import DEM_demo_psychosis
from .DEM_demo_song_inference import DEM_demo_song_inference
from .DEM_demo_song_omission import DEM_demo_song_omission
from .DEM_demo_song_priors import DEM_demo_song_priors
from .DEM_demo_texture import DEM_demo_texture
from .DEM_evidence_accumulation import DEM_evidence_accumulation
from .DEM_get_faces import DEM_get_faces
from .DEM_morphogenesis import DEM_morphogenesis
from .DEM_path_integrals import DEM_path_integrals
from .DEM_psychophysics import DEM_psychophysics
from .DEM_self_entropy import DEM_self_entropy
from .DEM_sharing import DEM_sharing
from .DEM_spatial_deconvolution import DEM_spatial_deconvolution
from .DEM_surveillance import DEM_surveillance
from .DEM_vaccination import DEM_vaccination
from .DFP_demo_double_well import DFP_demo_double_well
from .DFP_demo_hdm import DFP_demo_hdm
from .FEP_MB_demo import FEP_MB_demo
from .FEP_Manifold import FEP_Manifold
from .FEP_fluctuations import FEP_fluctuations
from .FEP_information_length import FEP_information_length
from .FEP_lorenz_surprise import FEP_lorenz_surprise
from .FEP_physics import FEP_physics
from .FEP_self_entropy import FEP_self_entropy
from .KLDemo import KLDemo
from .MDP_DEM_Mixed_Models_Movement import MDP_DEM_Mixed_Models_Movement
from .MDP_DEM_Oculomotion_Pharma_demo import MDP_DEM_Oculomotion_Pharma_demo
from .MDP_DEM_Oculomotion_demo import MDP_DEM_Oculomotion_demo
from .MDP_Heart_Beat import MDP_Heart_Beat
from .Markov_blankets_and_NESS import Markov_blankets_and_NESS
from .expmall import expmall
from .ndstest import ndstest
from .spm_ADEM_cue_rt import spm_ADEM_cue_rt
from .spm_ADEM_set_rt import spm_ADEM_set_rt
from .spm_CLIMATE_ci import spm_CLIMATE_ci
from .spm_CLIMATE_gen import spm_CLIMATE_gen
from .spm_CLIMATE_plot import spm_CLIMATE_plot
from .spm_CLIMATE_priors import spm_CLIMATE_priors
from .spm_COVID import spm_COVID
from .spm_COVID_B import spm_COVID_B
from .spm_COVID_BMR import spm_COVID_BMR
from .spm_COVID_PV import spm_COVID_PV
from .spm_COVID_R_cii import spm_COVID_R_cii
from .spm_COVID_S import spm_COVID_S
from .spm_COVID_SB import spm_COVID_SB
from .spm_COVID_T import spm_COVID_T
from .spm_COVID_TS import spm_COVID_TS
from .spm_COVID_US import spm_COVID_US
from .spm_COVID_Y import spm_COVID_Y
from .spm_COVID_ci import spm_COVID_ci
from .spm_COVID_dashboard import spm_COVID_dashboard
from .spm_COVID_gen import spm_COVID_gen
from .spm_COVID_plot import spm_COVID_plot
from .spm_COVID_priors import spm_COVID_priors
from .spm_COVID_priors_R import spm_COVID_priors_R
from .spm_COVID_table import spm_COVID_table
from .spm_DEM_ButtonDownFcn import spm_DEM_ButtonDownFcn
from .spm_DEM_EEG import spm_DEM_EEG
from .spm_DEM_M import spm_DEM_M
from .spm_DEM_MEG import spm_DEM_MEG
from .spm_DEM_T import spm_DEM_T
from .spm_DEM_basis import spm_DEM_basis
from .spm_DEM_movie import spm_DEM_movie
from .spm_DEM_play import spm_DEM_play
from .spm_DEM_play_song import spm_DEM_play_song
from .spm_DEM_qC import spm_DEM_qC
from .spm_Lap2Lorenz import spm_Lap2Lorenz
from .spm_MDP import spm_MDP
from .spm_MDP_DEM import spm_MDP_DEM
from .spm_MDP_DP import spm_MDP_DP
from .spm_MDP_F import spm_MDP_F
from .spm_MDP_G import spm_MDP_G
from .spm_MDP_L import spm_MDP_L
from .spm_MDP_VB import spm_MDP_VB
from .spm_MDP_VB_ERP import spm_MDP_VB_ERP
from .spm_MDP_VB_LFP import spm_MDP_VB_LFP
from .spm_MDP_VB_X import spm_MDP_VB_X
from .spm_MDP_VB_XX import spm_MDP_VB_XX
from .spm_MDP_VB_XXX import spm_MDP_VB_XXX
from .spm_MDP_VB_game import spm_MDP_VB_game
from .spm_MDP_VB_sleep import spm_MDP_VB_sleep
from .spm_MDP_VB_trial import spm_MDP_VB_trial
from .spm_MDP_VB_update import spm_MDP_VB_update
from .spm_MDP_check import spm_MDP_check
from .spm_MDP_factor_graph import spm_MDP_factor_graph
from .spm_MDP_game import spm_MDP_game
from .spm_MDP_game_KL import spm_MDP_game_KL
from .spm_MDP_game_optimism import spm_MDP_game_optimism
from .spm_MDP_link import spm_MDP_link
from .spm_MDP_log_evidence import spm_MDP_log_evidence
from .spm_MDP_mountain_car import spm_MDP_mountain_car
from .spm_MDP_offer import spm_MDP_offer
from .spm_MDP_plot import spm_MDP_plot
from .spm_MDP_size import spm_MDP_size
from .spm_MDP_structure_learning import spm_MDP_structure_learning
from .spm_MDP_trust import spm_MDP_trust
from .spm_MDP_urn import spm_MDP_urn
from .spm_NESS_constraints import spm_NESS_constraints
from .spm_SARS_ci import spm_SARS_ci
from .spm_SARS_gen import spm_SARS_gen
from .spm_SARS_plot import spm_SARS_plot
from .spm_SARS_priors import spm_SARS_priors
from .spm_SARS_priors_B import spm_SARS_priors_B
from .spm_SCK import spm_SCK
from .spm_SHC_fx import spm_SHC_fx
from .spm_cornsweet import spm_cornsweet
from .spm_cost_SHC_fx import spm_cost_SHC_fx
from .spm_cost_SHC_fxa import spm_cost_SHC_fxa
from .spm_cost_SHC_path import spm_cost_SHC_path
from .spm_cost_fx import spm_cost_fx
from .spm_cost_fxa import spm_cost_fxa
from .spm_dem_ERP import spm_dem_ERP
from .spm_dem_cue_movie import spm_dem_cue_movie
from .spm_dem_initialise import spm_dem_initialise
from .spm_dem_mdp_movie import spm_dem_mdp_movie
from .spm_dem_occlusion_movie import spm_dem_occlusion_movie
from .spm_dem_pursuit_movie import spm_dem_pursuit_movie
from .spm_dem_reach_movie import spm_dem_reach_movie
from .spm_dem_reach_plot import spm_dem_reach_plot
from .spm_dem_reach_x2J import spm_dem_reach_x2J
from .spm_dem_search_movie import spm_dem_search_movie
from .spm_dem_search_plot import spm_dem_search_plot
from .spm_dem_search_trajectory import spm_dem_search_trajectory
from .spm_dem_set_movie import spm_dem_set_movie
from .spm_diff_all import spm_diff_all
from .spm_find_internal import spm_find_internal
from .spm_fx_Gabor import spm_fx_Gabor
from .spm_fx_Lagrangian import spm_fx_Lagrangian
from .spm_fx_adem_cue import spm_fx_adem_cue
from .spm_fx_adem_pursuit import spm_fx_adem_pursuit
from .spm_fx_adem_reach import spm_fx_adem_reach
from .spm_fx_adem_salience import spm_fx_adem_salience
from .spm_fx_adem_write import spm_fx_adem_write
from .spm_fx_dem_cue import spm_fx_dem_cue
from .spm_fx_dem_observe import spm_fx_dem_observe
from .spm_fx_dem_pursuit import spm_fx_dem_pursuit
from .spm_fx_dem_reach import spm_fx_dem_reach
from .spm_fx_dem_salience import spm_fx_dem_salience
from .spm_fx_dem_write import spm_fx_dem_write
from .spm_fx_hdm_sck import spm_fx_hdm_sck
from .spm_fx_mountaincar import spm_fx_mountaincar
from .spm_fx_mountaincar_Q import spm_fx_mountaincar_Q
from .spm_gamma_log_evidence import spm_gamma_log_evidence
from .spm_gx_Gabor import spm_gx_Gabor
from .spm_gx_SHC import spm_gx_SHC
from .spm_gx_adem_cue import spm_gx_adem_cue
from .spm_gx_adem_pursuit import spm_gx_adem_pursuit
from .spm_gx_adem_reach import spm_gx_adem_reach
from .spm_gx_adem_salience import spm_gx_adem_salience
from .spm_gx_adem_write import spm_gx_adem_write
from .spm_gx_dem_cue import spm_gx_dem_cue
from .spm_gx_dem_pursuit import spm_gx_dem_pursuit
from .spm_gx_dem_reach import spm_gx_dem_reach
from .spm_gx_dem_salience import spm_gx_dem_salience
from .spm_gx_dem_write import spm_gx_dem_write
from .spm_gx_hdm_sck import spm_gx_hdm_sck
from .spm_ho_gm import spm_ho_gm
from .spm_ho_poly import spm_ho_poly
from .spm_immune import spm_immune
from .spm_immune_gen import spm_immune_gen
from .spm_immune_plot import spm_immune_plot
from .spm_immune_priors import spm_immune_priors
from .spm_mc_fx import spm_mc_fx
from .spm_mc_fx_1 import spm_mc_fx_1
from .spm_mc_fx_2 import spm_mc_fx_2
from .spm_mc_fx_3 import spm_mc_fx_3
from .spm_mc_fx_4 import spm_mc_fx_4
from .spm_mc_fx_5 import spm_mc_fx_5
from .spm_mc_fxa_4 import spm_mc_fxa_4
from .spm_mc_fxa_5 import spm_mc_fxa_5
from .spm_mc_loss_C import spm_mc_loss_C
from .spm_mc_loss_G import spm_mc_loss_G
from .spm_meta_model import spm_meta_model
from .spm_mountaincar_Q import spm_mountaincar_Q
from .spm_mountaincar_fun import spm_mountaincar_fun
from .spm_mountaincar_movie import spm_mountaincar_movie
from .spm_multinomial_log_evidence import spm_multinomial_log_evidence
from .spm_salience_map import spm_salience_map
from .spm_voice import spm_voice
from .spm_voice_FS import spm_voice_FS
from .spm_voice_P300 import spm_voice_P300
from .spm_voice_Q import spm_voice_Q
from .spm_voice_check import spm_voice_check
from .spm_voice_dct import spm_voice_dct
from .spm_voice_ff import spm_voice_ff
from .spm_voice_filter import spm_voice_filter
from .spm_voice_frequency import spm_voice_frequency
from .spm_voice_fundamental import spm_voice_fundamental
from .spm_voice_get_LEX import spm_voice_get_LEX
from .spm_voice_get_next import spm_voice_get_next
from .spm_voice_get_word import spm_voice_get_word
from .spm_voice_get_xY import spm_voice_get_xY
from .spm_voice_i import spm_voice_i
from .spm_voice_iQ import spm_voice_iQ
from .spm_voice_identity import spm_voice_identity
from .spm_voice_iff import spm_voice_iff
from .spm_voice_likelihood import spm_voice_likelihood
from .spm_voice_onset import spm_voice_onset
from .spm_voice_onsets import spm_voice_onsets
from .spm_voice_read import spm_voice_read
from .spm_voice_repeat import spm_voice_repeat
from .spm_voice_segmentation import spm_voice_segmentation
from .spm_voice_speak import spm_voice_speak
from .spm_voice_test import spm_voice_test
from .spm_voice_warp import spm_voice_warp

