from spm.__wrap__ import _Runtime


def spm_DEM_EEG(*args, **kwargs):
  """  simulated electrophysiological response based on conditional estimates  
    FORMAT [R] = spm_DEM_EEG(DEM,dt,n,graphics)  
    DEM  - DEM structure  
    dt   - time bin (seconds)  
    n    - level[s]  
    g    - graphics switch  
     
    R{i} - response over peri-stimulus time (whitened error): level i  
     
    These simulated response assume that LFPs are generated by superficial  
    pyramidal cells that correspond to units encoding precision-weighted  
    prediction error.  
     
    see also spm_DEM_ERP  
   __________________________________________________________________________  
  

  [Link to the Matlab implementation.](https://github.com/spm/spm/blob/main/toolbox/DEM/spm_DEM_EEG.m)
  """

  return _Runtime.call("spm_DEM_EEG", *args, **kwargs)
